title: Andrea Bruera
logo: cover.jpg
description: PhD Student in Computer Science <br> Queen Mary University of London
email: a.bruera@qmul.ac.uk
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
