title: Andrea Bruera
logo: cover.jpg
description: Postdoctoral researcher <br> Max Planck Institute for Human Cognitive and Brain Sciences <br>
email: a.bruera@qmul.ac.uk
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
