title: Andrea Bruera
logo: cover.jpg
description: Postdoctoral researcher <br> Max Planck Institute for Human Cognitive and Brain Sciences <br>
email: bruera@cbs.mpg.de
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
